/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NotificationType = IDL.Variant({
  'examReminder' : IDL.Null,
  'general' : IDL.Null,
  'assignmentReminder' : IDL.Null,
});
export const Time = IDL.Int;
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'notificationType' : NotificationType,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const PerformanceData = IDL.Record({
  'month' : IDL.Nat,
  'marksPercent' : IDL.Nat,
  'subjectId' : IDL.Nat,
  'attendancePercent' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Assignment = IDL.Record({
  'id' : IDL.Nat,
  'isSubmitted' : IDL.Bool,
  'title' : IDL.Text,
  'dueDate' : Time,
  'submittedAt' : IDL.Opt(Time),
  'description' : IDL.Text,
  'subjectId' : IDL.Nat,
});
export const CalendarEventType = IDL.Variant({
  'practical' : IDL.Null,
  'assignment' : IDL.Null,
  'exam' : IDL.Null,
  'holiday' : IDL.Null,
});
export const CalendarEvent = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
  'eventType' : CalendarEventType,
});
export const Subject = IDL.Record({
  'id' : IDL.Nat,
  'professorName' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'marksObtained' : IDL.Nat,
  'practicalDate' : Time,
  'name' : IDL.Text,
  'maxMarks' : IDL.Nat,
  'attendancePercent' : IDL.Nat,
  'examDate' : Time,
});
export const StudentProfile = IDL.Record({
  'studentId' : IDL.Text,
  'profileImage' : IDL.Text,
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'course' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'isRead' : IDL.Bool,
  'receiverId' : IDL.Principal,
  'timestamp' : Time,
  'senderId' : IDL.Principal,
});
export const ChatMessageInput = IDL.Record({
  'content' : IDL.Text,
  'receiverId' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addNotification' : IDL.Func([Notification, IDL.Principal], [IDL.Nat], []),
  'addPerformanceData' : IDL.Func([PerformanceData], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAssignment' : IDL.Func([Assignment], [IDL.Nat], []),
  'createCalendarEvent' : IDL.Func([CalendarEvent], [IDL.Nat], []),
  'createSubject' : IDL.Func([Subject], [IDL.Nat], []),
  'getAllAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
  'getAllCalendarEvents' : IDL.Func([], [IDL.Vec(CalendarEvent)], ['query']),
  'getAllStudentProfiles' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
  'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPerformanceData' : IDL.Func([], [IDL.Vec(PerformanceData)], ['query']),
  'getStudentProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(StudentProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([StudentProfile], [], []),
  'saveStudentProfile' : IDL.Func([StudentProfile], [], []),
  'seedDemoData' : IDL.Func([], [], []),
  'sendMessage' : IDL.Func([ChatMessageInput], [IDL.Nat], []),
  'submitAssignment' : IDL.Func([IDL.Nat], [], []),
  'updateSubject' : IDL.Func([Subject], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NotificationType = IDL.Variant({
    'examReminder' : IDL.Null,
    'general' : IDL.Null,
    'assignmentReminder' : IDL.Null,
  });
  const Time = IDL.Int;
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'notificationType' : NotificationType,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const PerformanceData = IDL.Record({
    'month' : IDL.Nat,
    'marksPercent' : IDL.Nat,
    'subjectId' : IDL.Nat,
    'attendancePercent' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Assignment = IDL.Record({
    'id' : IDL.Nat,
    'isSubmitted' : IDL.Bool,
    'title' : IDL.Text,
    'dueDate' : Time,
    'submittedAt' : IDL.Opt(Time),
    'description' : IDL.Text,
    'subjectId' : IDL.Nat,
  });
  const CalendarEventType = IDL.Variant({
    'practical' : IDL.Null,
    'assignment' : IDL.Null,
    'exam' : IDL.Null,
    'holiday' : IDL.Null,
  });
  const CalendarEvent = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
    'eventType' : CalendarEventType,
  });
  const Subject = IDL.Record({
    'id' : IDL.Nat,
    'professorName' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'marksObtained' : IDL.Nat,
    'practicalDate' : Time,
    'name' : IDL.Text,
    'maxMarks' : IDL.Nat,
    'attendancePercent' : IDL.Nat,
    'examDate' : Time,
  });
  const StudentProfile = IDL.Record({
    'studentId' : IDL.Text,
    'profileImage' : IDL.Text,
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'course' : IDL.Text,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'isRead' : IDL.Bool,
    'receiverId' : IDL.Principal,
    'timestamp' : Time,
    'senderId' : IDL.Principal,
  });
  const ChatMessageInput = IDL.Record({
    'content' : IDL.Text,
    'receiverId' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addNotification' : IDL.Func([Notification, IDL.Principal], [IDL.Nat], []),
    'addPerformanceData' : IDL.Func([PerformanceData], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAssignment' : IDL.Func([Assignment], [IDL.Nat], []),
    'createCalendarEvent' : IDL.Func([CalendarEvent], [IDL.Nat], []),
    'createSubject' : IDL.Func([Subject], [IDL.Nat], []),
    'getAllAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
    'getAllCalendarEvents' : IDL.Func([], [IDL.Vec(CalendarEvent)], ['query']),
    'getAllStudentProfiles' : IDL.Func(
        [],
        [IDL.Vec(StudentProfile)],
        ['query'],
      ),
    'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPerformanceData' : IDL.Func([], [IDL.Vec(PerformanceData)], ['query']),
    'getStudentProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(StudentProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([StudentProfile], [], []),
    'saveStudentProfile' : IDL.Func([StudentProfile], [], []),
    'seedDemoData' : IDL.Func([], [], []),
    'sendMessage' : IDL.Func([ChatMessageInput], [IDL.Nat], []),
    'submitAssignment' : IDL.Func([IDL.Nat], [], []),
    'updateSubject' : IDL.Func([Subject], [], []),
  });
};

export const init = ({ IDL }) => { return []; };