/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Assignment {
  'id' : bigint,
  'isSubmitted' : boolean,
  'title' : string,
  'dueDate' : Time,
  'submittedAt' : [] | [Time],
  'description' : string,
  'subjectId' : bigint,
}
export interface CalendarEvent {
  'id' : bigint,
  'title' : string,
  'date' : Time,
  'description' : string,
  'eventType' : CalendarEventType,
}
export type CalendarEventType = { 'practical' : null } |
  { 'assignment' : null } |
  { 'exam' : null } |
  { 'holiday' : null };
export interface ChatMessage {
  'id' : bigint,
  'content' : string,
  'isRead' : boolean,
  'receiverId' : Principal,
  'timestamp' : Time,
  'senderId' : Principal,
}
export interface ChatMessageInput {
  'content' : string,
  'receiverId' : Principal,
}
export interface Notification {
  'id' : bigint,
  'title' : string,
  'notificationType' : NotificationType,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : Time,
}
export type NotificationType = { 'examReminder' : null } |
  { 'general' : null } |
  { 'assignmentReminder' : null };
export interface PerformanceData {
  'month' : bigint,
  'marksPercent' : bigint,
  'subjectId' : bigint,
  'attendancePercent' : bigint,
}
export interface StudentProfile {
  'studentId' : string,
  'profileImage' : string,
  'name' : string,
  'year' : bigint,
  'email' : string,
  'phone' : string,
  'course' : string,
}
export interface Subject {
  'id' : bigint,
  'professorName' : string,
  'isCompleted' : boolean,
  'marksObtained' : bigint,
  'practicalDate' : Time,
  'name' : string,
  'maxMarks' : bigint,
  'attendancePercent' : bigint,
  'examDate' : Time,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addNotification' : ActorMethod<[Notification, Principal], bigint>,
  'addPerformanceData' : ActorMethod<[PerformanceData], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAssignment' : ActorMethod<[Assignment], bigint>,
  'createCalendarEvent' : ActorMethod<[CalendarEvent], bigint>,
  'createSubject' : ActorMethod<[Subject], bigint>,
  'getAllAssignments' : ActorMethod<[], Array<Assignment>>,
  'getAllCalendarEvents' : ActorMethod<[], Array<CalendarEvent>>,
  'getAllStudentProfiles' : ActorMethod<[], Array<StudentProfile>>,
  'getAllSubjects' : ActorMethod<[], Array<Subject>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [StudentProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatHistory' : ActorMethod<[Principal], Array<ChatMessage>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPerformanceData' : ActorMethod<[], Array<PerformanceData>>,
  'getStudentProfile' : ActorMethod<[], [] | [StudentProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [StudentProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[StudentProfile], undefined>,
  'saveStudentProfile' : ActorMethod<[StudentProfile], undefined>,
  'seedDemoData' : ActorMethod<[], undefined>,
  'sendMessage' : ActorMethod<[ChatMessageInput], bigint>,
  'submitAssignment' : ActorMethod<[bigint], undefined>,
  'updateSubject' : ActorMethod<[Subject], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];