/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface StudentProfile {
    studentId: string;
    profileImage: string;
    name: string;
    year: bigint;
    email: string;
    phone: string;
    course: string;
}
export type Time = bigint;
export interface ChatMessageInput {
    content: string;
    receiverId: Principal;
}
export interface Notification {
    id: bigint;
    title: string;
    notificationType: NotificationType;
    isRead: boolean;
    message: string;
    timestamp: Time;
}
export interface CalendarEvent {
    id: bigint;
    title: string;
    date: Time;
    description: string;
    eventType: CalendarEventType;
}
export interface ChatMessage {
    id: bigint;
    content: string;
    isRead: boolean;
    receiverId: Principal;
    timestamp: Time;
    senderId: Principal;
}
export interface Assignment {
    id: bigint;
    isSubmitted: boolean;
    title: string;
    dueDate: Time;
    submittedAt?: Time;
    description: string;
    subjectId: bigint;
}
export interface PerformanceData {
    month: bigint;
    marksPercent: bigint;
    subjectId: bigint;
    attendancePercent: bigint;
}
export interface Subject {
    id: bigint;
    professorName: string;
    isCompleted: boolean;
    marksObtained: bigint;
    practicalDate: Time;
    name: string;
    maxMarks: bigint;
    attendancePercent: bigint;
    examDate: Time;
}
export enum CalendarEventType {
    practical = "practical",
    assignment = "assignment",
    exam = "exam",
    holiday = "holiday"
}
export enum NotificationType {
    examReminder = "examReminder",
    general = "general",
    assignmentReminder = "assignmentReminder"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addNotification(notification: Notification, receiver: Principal): Promise<bigint>;
    addPerformanceData(data: PerformanceData): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAssignment(assignment: Assignment): Promise<bigint>;
    createCalendarEvent(event: CalendarEvent): Promise<bigint>;
    createSubject(subject: Subject): Promise<bigint>;
    getAllAssignments(): Promise<Array<Assignment>>;
    getAllCalendarEvents(): Promise<Array<CalendarEvent>>;
    getAllStudentProfiles(): Promise<Array<StudentProfile>>;
    getAllSubjects(): Promise<Array<Subject>>;
    getCallerUserProfile(): Promise<StudentProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChatHistory(withUser: Principal): Promise<Array<ChatMessage>>;
    getNotifications(): Promise<Array<Notification>>;
    getPerformanceData(): Promise<Array<PerformanceData>>;
    getStudentProfile(): Promise<StudentProfile | null>;
    getUserProfile(user: Principal): Promise<StudentProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: StudentProfile): Promise<void>;
    saveStudentProfile(profile: StudentProfile): Promise<void>;
    seedDemoData(): Promise<void>;
    sendMessage(input: ChatMessageInput): Promise<bigint>;
    submitAssignment(assignmentId: bigint): Promise<void>;
    updateSubject(subject: Subject): Promise<void>;
}
import type { Assignment as _Assignment, CalendarEvent as _CalendarEvent, CalendarEventType as _CalendarEventType, Notification as _Notification, NotificationType as _NotificationType, StudentProfile as _StudentProfile, Time as _Time, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addNotification(arg0: Notification, arg1: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addNotification(to_candid_Notification_n1(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNotification(to_candid_Notification_n1(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async addPerformanceData(arg0: PerformanceData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPerformanceData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPerformanceData(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAssignment(arg0: Assignment): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAssignment(to_candid_Assignment_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAssignment(to_candid_Assignment_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createCalendarEvent(arg0: CalendarEvent): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCalendarEvent(to_candid_CalendarEvent_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCalendarEvent(to_candid_CalendarEvent_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createSubject(arg0: Subject): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubject(arg0);
            return result;
        }
    }
    async getAllAssignments(): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssignments();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssignments();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCalendarEvents(): Promise<Array<CalendarEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCalendarEvents();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCalendarEvents();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStudentProfiles(): Promise<Array<StudentProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudentProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudentProfiles();
            return result;
        }
    }
    async getAllSubjects(): Promise<Array<Subject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubjects();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<StudentProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatHistory(arg0: Principal): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatHistory(arg0);
            return result;
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPerformanceData(): Promise<Array<PerformanceData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPerformanceData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPerformanceData();
            return result;
        }
    }
    async getStudentProfile(): Promise<StudentProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<StudentProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: StudentProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveStudentProfile(arg0: StudentProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveStudentProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveStudentProfile(arg0);
            return result;
        }
    }
    async seedDemoData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedDemoData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedDemoData();
            return result;
        }
    }
    async sendMessage(arg0: ChatMessageInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0);
            return result;
        }
    }
    async submitAssignment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAssignment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAssignment(arg0);
            return result;
        }
    }
    async updateSubject(arg0: Subject): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubject(arg0);
            return result;
        }
    }
}
function from_candid_Assignment_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Assignment): Assignment {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_CalendarEventType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CalendarEventType): CalendarEventType {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_CalendarEvent_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CalendarEvent): CalendarEvent {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentProfile]): StudentProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    isSubmitted: boolean;
    title: string;
    dueDate: _Time;
    submittedAt: [] | [_Time];
    description: string;
    subjectId: bigint;
}): {
    id: bigint;
    isSubmitted: boolean;
    title: string;
    dueDate: Time;
    submittedAt?: Time;
    description: string;
    subjectId: bigint;
} {
    return {
        id: value.id,
        isSubmitted: value.isSubmitted,
        title: value.title,
        dueDate: value.dueDate,
        submittedAt: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.submittedAt)),
        description: value.description,
        subjectId: value.subjectId
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    date: _Time;
    description: string;
    eventType: _CalendarEventType;
}): {
    id: bigint;
    title: string;
    date: Time;
    description: string;
    eventType: CalendarEventType;
} {
    return {
        id: value.id,
        title: value.title,
        date: value.date,
        description: value.description,
        eventType: from_candid_CalendarEventType_n20(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    notificationType: _NotificationType;
    isRead: boolean;
    message: string;
    timestamp: _Time;
}): {
    id: bigint;
    title: string;
    notificationType: NotificationType;
    isRead: boolean;
    message: string;
    timestamp: Time;
} {
    return {
        id: value.id,
        title: value.title,
        notificationType: from_candid_NotificationType_n28(_uploadFile, _downloadFile, value.notificationType),
        isRead: value.isRead,
        message: value.message,
        timestamp: value.timestamp
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    practical: null;
} | {
    assignment: null;
} | {
    exam: null;
} | {
    holiday: null;
}): CalendarEventType {
    return "practical" in value ? CalendarEventType.practical : "assignment" in value ? CalendarEventType.assignment : "exam" in value ? CalendarEventType.exam : "holiday" in value ? CalendarEventType.holiday : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    examReminder: null;
} | {
    general: null;
} | {
    assignmentReminder: null;
}): NotificationType {
    return "examReminder" in value ? NotificationType.examReminder : "general" in value ? NotificationType.general : "assignmentReminder" in value ? NotificationType.assignmentReminder : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Assignment>): Array<Assignment> {
    return value.map((x)=>from_candid_Assignment_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CalendarEvent>): Array<CalendarEvent> {
    return value.map((x)=>from_candid_CalendarEvent_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n26(_uploadFile, _downloadFile, x));
}
function to_candid_Assignment_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Assignment): _Assignment {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_CalendarEventType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CalendarEventType): _CalendarEventType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_CalendarEvent_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CalendarEvent): _CalendarEvent {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_NotificationType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType): _NotificationType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Notification_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Notification): _Notification {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    date: Time;
    description: string;
    eventType: CalendarEventType;
}): {
    id: bigint;
    title: string;
    date: _Time;
    description: string;
    eventType: _CalendarEventType;
} {
    return {
        id: value.id,
        title: value.title,
        date: value.date,
        description: value.description,
        eventType: to_candid_CalendarEventType_n11(_uploadFile, _downloadFile, value.eventType)
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    notificationType: NotificationType;
    isRead: boolean;
    message: string;
    timestamp: Time;
}): {
    id: bigint;
    title: string;
    notificationType: _NotificationType;
    isRead: boolean;
    message: string;
    timestamp: _Time;
} {
    return {
        id: value.id,
        title: value.title,
        notificationType: to_candid_NotificationType_n3(_uploadFile, _downloadFile, value.notificationType),
        isRead: value.isRead,
        message: value.message,
        timestamp: value.timestamp
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    isSubmitted: boolean;
    title: string;
    dueDate: Time;
    submittedAt?: Time;
    description: string;
    subjectId: bigint;
}): {
    id: bigint;
    isSubmitted: boolean;
    title: string;
    dueDate: _Time;
    submittedAt: [] | [_Time];
    description: string;
    subjectId: bigint;
} {
    return {
        id: value.id,
        isSubmitted: value.isSubmitted,
        title: value.title,
        dueDate: value.dueDate,
        submittedAt: value.submittedAt ? candid_some(value.submittedAt) : candid_none(),
        description: value.description,
        subjectId: value.subjectId
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CalendarEventType): {
    practical: null;
} | {
    assignment: null;
} | {
    exam: null;
} | {
    holiday: null;
} {
    return value == CalendarEventType.practical ? {
        practical: null
    } : value == CalendarEventType.assignment ? {
        assignment: null
    } : value == CalendarEventType.exam ? {
        exam: null
    } : value == CalendarEventType.holiday ? {
        holiday: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType): {
    examReminder: null;
} | {
    general: null;
} | {
    assignmentReminder: null;
} {
    return value == NotificationType.examReminder ? {
        examReminder: null
    } : value == NotificationType.general ? {
        general: null
    } : value == NotificationType.assignmentReminder ? {
        assignmentReminder: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
